# settings for code execution
exec:
  timeout: 600

# inference_engine: vllm

agent:
  steps: 25
  # LLM settings for coding
  code:
    model: gpt-4-turbo #"deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" #"RedHatAI/DeepSeek-R1-Distill-Qwen-32B-FP8-dynamic" #  "RedHatAI/DeepSeek-R1-Distill-Qwen-32B-FP8-dynamic" # deepseek-ai/DeepSeek-R1-Distill-Qwen-14B #"neuralmagic/DeepSeek-R1-Distill-Qwen-32B-dynamic"  #
    temp: 0.6
    max_new_tokens:  3200
    top_p : 0.95
    top_k : 50
    num_return_sequences : 1
