vars:
  step_count: &step_count 500
  time_limit: &time_limit 7200 # 2 hours

defaults: &defaults
  start: aide-deepseek-coder/start.sh
  dockerfile: aide-deepseek-coder/Dockerfile
  kwargs_type: omegaconf
  env_vars: &env_vars
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count

kwargs_common: &kwargs_common
  agent.search.max_debug_depth: 20
  agent.search.debug_prob: 1
  agent.time_limit: *time_limit
  exec.timeout: 7200
  copy_data: False

aide-deepseek-coder:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: deepseek-coder-33b-instruct
    agent.feedback.model: deepseek-coder-33b-instruct
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

aide-deepseek-coder/dev:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: deepseek-coder-33b-instruct
    agent.feedback.model: deepseek-coder-33b-instruct
    agent.steps: 8
  env_vars:
    <<: *env_vars
    HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }} 